version: "3.7"

services:
  
  fastapi: &fastapi-app-base
    build:
      context: ./fastapi
    volumes:
      - ./ml-models:/opt/app/ml-models
      - ./fastapi/app.py:/opt/app/app.py
      - ./fastapi/schemas.py:/opt/app/schemas.py
      - ./gunicorn.py:/opt/app/gunicorn.py
    ports:
      - "8080:8080"
    env_file:
      - ./envs/.env
    command: /bin/bash
  fastapi-app-dev:
    <<: *fastapi-app-base
    command: uvicorn --reload --workers 1 --host 0.0.0.0 --port 8080 app:app
  fastapi-app-prod:
    <<: *fastapi-app-base
    environment:
      WORKER_CLASS: uvicorn.workers.UvicornWorker
    command: gunicorn -c gunicorn.py app:app
